### ISSUE TITLE
GPU Computing

### ISSUE THREAD

**Issue by jacaseyclyde** [sjsu-high-z-classify/GalNet#17]
**Is your feature request related to a problem? Please describe.**
Deep learning models are big, and can take a long time to train.

**Describe the solution you'd like**
We should parallelize our models on one or more GPUs, as available.

**Describe alternatives you've considered**
We could also try distributing over MPI. This could be complicated however.

**Additional context**
None.

**Comment by ebarriosc1** [comment]
When do you need this completed by?

**Comment by jacaseyclyde** [comment]
no hard deadline yet, so just keeping working at whatever pace you're comfortable with (getting up to speed on the rest of the project first). we're just trying to get everything organized, with people assigned to the right tasks right now. planning on going through to update issues with milestones (and also assign them to projects) later
